### ISSUE TITLE
Errors on Tetris Fastboot Flasher 

### ISSUE THREAD

**Issue by Heptex** [HELLBOY017/Pong_fastboot_flasher#10]
@spike0en 
I used the Tetris Fastboot Flasher script and somehow it's throwing error like “boot.img not found” even though boot img is inside the folder I am using the script in.
![IMG_20241031_222340_822](https://github.com/user-attachments/assets/07ea7fa1-8abd-4a85-95a8-104509948336)

Please try to fix this or help me if I am doing something wrong 
My TG ID is **@heptexx**

**Comment by HELLBOY017** [comment]
I don't know specifically what tetris fastboot flasher script is so I'm just gonna close this issue.

**Comment by Heptex** [comment]
> I don't know specifically what tetris fastboot flasher script is so I'm just gonna close this issue.

**Comment by Heptex** [comment]
Here it is https://github.com/spike0en/Nothing_Fastboot_Flasher/blob/tetris/Linux/flash_all.sh

**Comment by HELLBOY017** [comment]
Not related to this repo
