### ISSUE TITLE
Getting error after downloading the platform tools in the script

### ISSUE THREAD

**Issue by TronTheGamer** [HELLBOY017/Pong_fastboot_flasher#8]
[PC OS Version] Windows 11 23H2
[Description]
I am getting the following error when running the `flash_all.bat` file just after the part where platform tools are downloaded:

```pwsh
Microsoft VBScript runtime error: Object required: 'objShell.NameSpace(...)'
```
![image](https://github.com/user-attachments/assets/e4e598af-363a-4519-8939-15db4c17b8e2)

**Comment by HELLBOY017** [comment]
Should be fixed now:-
https://github.com/HELLBOY017/Pong_fastboot_flasher/commit/df9a64f6104285d3bae2b6c8da6492a8559ab448
